### ISSUE TITLE
LedControl.h:54: error: 'byte' has not been declared

### ISSUE THREAD

**Issue by darkomen** [wayoda/LedControl#3]
Hello, I'm trying to use the library, with a arduino duemilanove and Arduino IDE 1.0.5 under mac 10.9.4.
When I compile any DEMO i get the following error:
/Applications/Arduino.app/Contents/Resources/Java/libraries/LedControl/LedControl.h:54: error: 'byte' does not name a type

I don't know which is the problem, please can you help me?

Best regards.

**Comment by wayoda** [comment]
I guess it was not a problem with the library in the end?
I closing it now, feel free  to reopen the issue if the problem pertains.

Eberhard
