### ISSUE TITLE
MAX7219 not working with ESP32 anymore

### ISSUE THREAD

**Issue by ShoootLight** [wayoda/LedControl#30]
The MAX7219 is not working together with my NodeMCU ESP32-S anymore. It did around a half year ago, but then I stopped programming with the LED Matrix.
When I upload a sketch it lights up all four or three out of four segments fully up (every pixel is bright doesn't matter what I've programmed), but when I plug it into my computer nothing happens.

I tried both ways of installing the Arduino Core ([Board Manager](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md) and [Windows](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/windows.md)) and made the [avr/pgmspace.h fix](https://github.com/espressif/arduino-esp32/issues/508).
Does anyone have the same problem?

Thank you in advance

**Comment by ShoootLight** [comment]
The problem was the wrong pins. I now use P32, P33 and P25.
Thanks to all of [those guys](https://github.com/espressif/arduino-esp32/issues/1914) for their help!

**Comment by stephanschulz** [comment]
Same for me `LedControl lc=LedControl(32,33,25,2); // feather esp32 v1` allowed me to use this library with adafruit feather esp32 v1

but I do have to use this fork
https://github.com/GitCodeGoose/LedControl/tree/fix_pgmspace_include
